ktree = ... 
    KinematicTree( ... % Chest
        Quaternion([1,0,0,0]), ...
        Quaternion([0,0,0,0]), ...
        Quaternion([0,0,0,0]), ...
        [ ...
            KinematicTree( ... % Left shoulder
                Quaternion([1,0,0,0]), ...
                Quaternion([0,-1.5,0,0]), ...
                Quaternion([0,-.5,0,1]), ...
                [ ...
                    KinematicTree( ... % Left upper arm
                        Quaternion([1/sqrt(2),1/sqrt(2),0,0]), ...
                        Quaternion([0,0,3,0]), ...
                        Quaternion([0,0,0,0]), ...
                        [ ...
                            KinematicTree( ... % Left forearm
                                Quaternion([1,0,0,0]), ...
                                Quaternion([0,0,3,0]), ...
                                Quaternion([0,0,0,0]), ...
                                [ ...
                                ] ...
                            ) ...
                        ] ...
                    ) ...
                ] ...
            ), ...
            KinematicTree(... % Right shoulder
                Quaternion([1,0,0,0]), ... 
                Quaternion([0,1.5,0,0]), ...
                Quaternion([0,0.5,0,1]), ...
                [ ...
                    KinematicTree( ... % Right upper arm
                        Quaternion([1/sqrt(2),1/sqrt(2),0,0]), ...
                        Quaternion([0,0,3,0]), ...
                        Quaternion([0,0,0,0]), ...
                        [ ...
                            KinematicTree( ... % Right forearm
                                Quaternion([1,0,0,0]), ...
                                Quaternion([0,0,3,0]), ...
                                Quaternion([0,0,0,0]), ...
                                [ ...
                                ] ...
                            ) ...
                        ] ...
                    ) ...
                ] ...
            ) 
        ] ...
    );

% 1 degree rotation about each axis
deg1z = Quaternion([0,0,1],pi/180);
deg1x = Quaternion([1,0,0],pi/180);
deg1y = Quaternion([0,1,0],pi/180);

degsPerStep = 6;

figure(1);
for i=1:(360/degsPerStep)
    for i = 1:degsPerStep
        ktree.sub(1).rotateAll(deg1z);
    end
    
    qs = ktree.getPoints();
    N = numel(qs);
    pts = zeros(3,N);
    for i=1:N
        pts(:,i) = qs(i).v();
    end

    disp(1)
    scatter3(pts(1,:),pts(2,:),pts(3,:))
    xlabel('x')
    ylabel('y')
    zlabel('z')
    axis([-8,8,-8,8,-8,8])
    pause(0.05)
end